mock_provider "aws" {}

mock_provider "aws" {
  alias = "us_east_1"
}

run "production_equivalent_local_plan" {
  command = plan

  override_data {
    target = module.network.data.aws_availability_zones.available
    values = {
      names = ["ap-northeast-2a", "ap-northeast-2c"]
    }
  }

  override_data {
    target = module.network.data.aws_region.current
    values = {
      name = "ap-northeast-2"
    }
  }

  override_data {
    target = module.compute.data.aws_region.current
    values = {
      name = "ap-northeast-2"
    }
  }

  variables {
    hosted_zone_id        = "Z0000000000000000000"
    company_domain        = "company.prod.example.com"
    applicant_domain      = "applicant.prod.example.com"
    api_image             = "000000000000.dkr.ecr.ap-northeast-2.amazonaws.com/iep-api:local"
    worker_image          = "000000000000.dkr.ecr.ap-northeast-2.amazonaws.com/iep-worker:local"
    interview_model_id    = "local-model-id"
    cognito_domain_prefix = "iep-prod-company"
  }

  assert {
    condition     = contains(keys(module.data.bucket_arns), "source")
    error_message = "source bucket must be part of the local plan"
  }

  assert {
    condition     = module.compute.api_service_name != ""
    error_message = "API service must be part of the local plan"
  }

  assert {
    condition     = contains(keys(module.edge.distribution_ids), "company")
    error_message = "company CloudFront distribution must be part of the local plan"
  }

  # The console reads login_domain, client_id and redirect_uri together or not at all --
  # `readCompanyAuthConfig` returns null when any one is missing and falls back to a demo
  # token the deployed API rejects. So an absent login domain is not a missing convenience,
  # it is a production console that builds, deploys, and cannot log anybody in.
  #
  # Only the two values a plan can resolve are asserted. `client_id` is generated by Cognito
  # at apply and is unknowable here; asserting it non-null would only be asserting that
  # Terraform had already created the pool.
  # A ternary rather than a null check inside `alltrue`, and not `coalesce` either: HCL
  # evaluates every element of the list before the function runs, so `strcontains(null, ...)`
  # aborts the run with an invalid-argument error and `coalesce(null, "")` fails on its own
  # rejection of empty strings. Either way the run dies without reporting the actual cause.
  assert {
    condition = alltrue([
      output.frontend.cognito.login_domain == null ? false : strcontains(output.frontend.cognito.login_domain, ".auth."),
      output.frontend.cognito.redirect_uri == "https://company.prod.example.com/auth/callback",
    ])
    error_message = "the console build needs a hosted login domain and its own origin as the redirect"
  }

  # The redirect the console will send must be one the pool accepts: Cognito rejects any
  # `redirect_uri` outside `callback_urls`, and the two are assembled in different roots from
  # different variables, so they can disagree while both look right in isolation.
  assert {
    condition = contains(
      module.identity.callback_urls,
      output.frontend.cognito.redirect_uri,
    )
    error_message = "the console redirect must be registered on the user pool client"
  }

  # A publish target that named the bucket but the wrong distribution would sync files nobody
  # is served and invalidate a cache nobody reads, with a green pipeline either way. Only the
  # URL is knowable before apply; the bucket name and distribution id are computed.
  assert {
    condition = alltrue([
      for site in values(output.frontend.sites) :
      startswith(site.url, "https://")
    ])
    error_message = "each site must carry the URL the publish job verifies against"
  }
}
